# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Hara's Log
paginate:       25
baseurl:        ""
url:            "https://haraprasadj.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Hara Prasad J
  # url:          http://chester.how
  email:        haraprasad@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/haraprasadj

# Gems
plugins:
  - jekyll-paginate
