# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Hara's Log
paginate:       10
baseurl:        ""
url:            "https://haraprasadj.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Hara Prasad J
  url:          http://www.haraprasad.com
  email:        haraprasad@gmail.com
  github:       haraprasadj
  linkedin:     haraprasadj
  twitter:      haraprasad_j
  stackoverflow: 4230286/haraprasadj

# Custom vars
version:        3.4.1

# Gems
plugins:
  - jekyll-paginate
