# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Hara's Log
paginate:       5
baseurl:        ""
url:            "https://haraprasadj.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Hara Prasad J
  url:          http://www.haraprasad.com
  email:        haraprasad@gmail.com
  github:       haraprasadj
  linkedin:     haraprasadj
  twitter:      haraprasad_j
  stackoverflow: 3462736/haraprasadj

social:
  name: Hara Prasad Juvvala
  links:
    - https://twitter.com/haraprasad_j
    - https://www.linkedin.com/in/haraprasadj
    - https://github.com/haraprasadj

# Custom vars
version:        3.4.1

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-include-cache

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.16.0"
